"""Restaurant service and repository contracts."""

from __future__ import annotations

from typing import Protocol


class RestaurantRepositoryContract(Protocol):
    """Shape expected from the restaurant repository."""

    def list_restaurants(self, filters: dict | None = None, sort: str | None = None): ...

    def list_favorite_restaurants(
        self,
        user,
        filters: dict | None = None,
        sort: str | None = None,
    ): ...

    def list_homepage_top_rated(self, *, limit: int = 5): ...

    def list_homepage_newest(self, *, limit: int = 5): ...

    def list_categories(self): ...

    def list_by_owner(self, owner): ...

    def get_by_slug(self, slug: str): ...

    def create(self, *, owner, data: dict): ...

    def save(self, restaurant, data: dict): ...

    def delete(self, restaurant) -> None: ...

    def list_menu_items(self, restaurant): ...

    def get_menu_item(self, *, restaurant, menu_item_id): ...

    def create_menu_item(self, *, restaurant, data: dict): ...

    def save_menu_item(self, menu_item, data: dict): ...

    def delete_menu_item(self, menu_item) -> None: ...

    def list_photos(self, restaurant): ...

    def create_photo(self, *, restaurant, file_id, sort_order: int = 0): ...

    def get_photo(self, *, restaurant, photo_id): ...

    def delete_photo(self, photo) -> None: ...

    def set_opening_hours(self, restaurant, hours_data: list): ...
