# Generated by Django 6.0.3 on 2026-04-29 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
