# Generated by Django 6.0.3 on 2026-04-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="files.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_item_images",
                to="files.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurant_logos",
                to="files.storedfile",
            ),
        ),
    ]
